{% set name = "sekve" %}
{% set version = "1.1.5" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5682c0d3320164a86d5ea43d4919f82015f6970c2830274857a3bb321be5f4c2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - matplotlib-base
    - numpy
    - pandas
    - scipy

test:
  imports:
    - sekve

about:
  home: https://gitlab.com/moscm/sekv-e
  summary: SEKV-E is a Python-based parameters extractor for the simplified EKV model.
  description: 'SEKV-E is a Python-based parameters extractor for the simplified EKV model, which is developed by ICLAB, EPFL. While it has been developed to serve the needs of low-power analog circuit designs.'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://people.epfl.ch/hung.han

extra:
  recipe-maintainers:
    - vicentetm
    - hung-chi
